apiVersion: v1
kind: Secret
metadata:
  name: featureos-secrets
  namespace: feature-os
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@featureos-postgres:5432/featureos?schema=public"
  JWT_SECRET: "featureos-production-super-secret-jwt-key-256-bit"
  JWT_REFRESH_SECRET: "featureos-production-super-secret-refresh-jwt-key"
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: ""
